{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:HelperTest", "name": "test_merkle_parent", "time": 0.0002694129943847656, "type": "error", "errtype": "builtins.NameError", "message": "name 'redouble_sha256' is not defined", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastesterelli/merkle-trees-jsong-pb-sf-072618/test/index_test.py\", line 10, in test_merkle_parent\n    self.assertEqual(merkle_parent(tx_hash0, tx_hash1), want)\n  File \"/home/jonastesterelli/merkle-trees-jsong-pb-sf-072618/index.ipynb\", line 84, in merkle_parent\n    ]\nNameError: name 'redouble_sha256' is not defined\n"}]}